[programs.localnet]
metajungle_solana = "7w8vbdxXoW8ezoQRukKfJGGywxe7DkqBxyTTctGesAs9"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/jeffery.yh.lin/.config/solana/id.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
